- job:
    name: stackviz-nodejs10-run-lint
    parent: nodejs-run-lint
    description: |
      Run lint using Node 10.
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/stackviz

- job:
    name: stackviz-nodejs10-run-test-browser
    parent: nodejs-run-test-browser
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/stackviz

- job:
    name: tempest-full-oldest-stable
    parent: tempest-full-py3
    # NOTE(gmann): This job supposed to test the oldest supported stable
    # release. We need to update the override-checkout once oldest
    # stable is moved to next stable release.
    override-checkout: stable/2023.2
    nodeset: openstack-single-node-jammy

- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
      - openstack-tox-pep8
      - openstack-tox-py38
      - openstack-tox-py39
      - openstack-tox-py310
      - openstack-tox-py311
      - openstack-tox-py312
      - stackviz-nodejs10-run-lint
      - stackviz-nodejs10-run-test-browser
      - tempest-full-py3:
          irrelevant-files: &irrelevant-files
            - ^.*\.rst$
            - ^doc/.*$
            - ^releasenotes/.*$
            - ^/stackviztests/.*$
            - ^.coveragerc$
            - ^.gitignore$
            - ^.gitreview$
      - tempest-full-oldest-stable:
          irrelevant-files: *irrelevant-files
    gate:
      jobs:
      - openstack-tox-pep8
      - openstack-tox-py38
      - openstack-tox-py39
      - openstack-tox-py310
      - openstack-tox-py311
      - openstack-tox-py312
      - stackviz-nodejs10-run-lint
      - stackviz-nodejs10-run-test-browser

    post:
      jobs:
        - publish-openstack-stackviz-element
