- job:
    name: stackviz-nodejs10-run-lint
    parent: nodejs-run-lint
    description: |
      Run lint using Node 10.
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/stackviz

- job:
    name: stackviz-nodejs10-run-test-browser
    parent: nodejs-run-test-browser
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/stackviz

- job:
    name: tempest-full-rocky
    parent: tempest-full-py3
    nodeset: openstack-single-node-xenial
    override-checkout: stable/rocky

- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-python35-jobs
      - openstack-python3-victoria-jobs
    check:
      jobs:
      - stackviz-nodejs10-run-lint
      - stackviz-nodejs10-run-test-browser
      - tempest-full-py3:
          irrelevant-files: &irrelevant-files
            - ^.*\.rst$
            - ^doc/.*$
            - ^releasenotes/.*$
            - ^/stackviztests/.*$
            - ^.coveragerc$
            - ^.gitignore$
            - ^.gitreview$
      - tempest-full-train-py3:
          irrelevant-files: *irrelevant-files
      - tempest-full-stein-py3:
          irrelevant-files: *irrelevant-files
      - tempest-full-rocky:
          irrelevant-files: *irrelevant-files
    gate:
      jobs:
      - stackviz-nodejs10-run-lint
      - stackviz-nodejs10-run-test-browser

    post:
      jobs:
        - publish-openstack-stackviz-element
