- job:
    name: stackviz-nodejs10-run-lint
    parent: nodejs-run-lint
    description: |
      Run lint using Node 10.
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/stackviz

- job:
    name: stackviz-nodejs10-run-test-browser
    parent: nodejs-run-test-browser
    vars:
      node_version: 10
    nodeset: ubuntu-focal
    pre-run: playbooks/nodejs/pre.yaml
    required-projects:
      - openstack/stackviz

- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
      - openstack-tox-pep8
      - openstack-tox-py35
      - openstack-tox-py36
      - openstack-tox-py37
      - openstack-tox-py38
      - openstack-tox-py39
      - openstack-tox-py310:
          voting: false
      - stackviz-nodejs10-run-lint
      - stackviz-nodejs10-run-test-browser
      - tempest-full-py3:
          irrelevant-files: &irrelevant-files
            - ^.*\.rst$
            - ^doc/.*$
            - ^releasenotes/.*$
            - ^/stackviztests/.*$
            - ^.coveragerc$
            - ^.gitignore$
            - ^.gitreview$
      - tempest-full-zed:
          irrelevant-files: *irrelevant-files
    gate:
      jobs:
      - openstack-tox-pep8
      - openstack-tox-py35
      - openstack-tox-py36
      - openstack-tox-py37
      - openstack-tox-py38
      - openstack-tox-py39
      - stackviz-nodejs10-run-lint
      - stackviz-nodejs10-run-test-browser

    post:
      jobs:
        - publish-openstack-stackviz-element
