- job:
    name: periodic-package-stackviz-element
    parent: legacy-publish-openstack-artifacts
    run: playbooks/legacy/periodic-package-stackviz-element/run.yaml
    post-run: playbooks/legacy/periodic-package-stackviz-element/post.yaml
    branches: master
    timeout: 1800

- project:
    templates:
      - nodejs8-jobs
      - openstack-python-jobs
      - publish-openstack-docs-pti
      - openstack-python36-jobs
      - openstack-python37-jobs
    periodic:
      jobs:
        - periodic-package-stackviz-element
